name: Publish NuGet Package
on:
  release:
      types:
        - published
        
jobs:
    build-and-publish-nuget:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./src/EducationTrail_CORE
      steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Build and Pack NueGet Package
          run: dotnet pack --configuration Release --output ./output
        - name: Publish Package to GitHub Packages
          run: dotnet nuget push ./output.*.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}