name: Publish NuGet Package
on:
  release:
      types:
        - published
        
jobs:
    build-and-publish-nuget:
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./src/EducationTrail_CORE
      steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 6.0.x
        - name: Restore dependencies
          run: dotnet restore
        - name: Add GitHub Nuget Source
          run: dotnet nuget add source --username ntohq --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/ntohq/index.json"
        - name: Build and Pack NuGet Package
          run: dotnet pack --configuration Release --output ./dist
        - name: Publish Package to GitHub Packages
          run: |
            cd dist
            dotnet nuget push *.nupkg --source "github" --api-key ${{ secrets.GITHUB_TOKEN }}